server:
  port: 8761
#  ssl:
#    enabled: true
#    key-store-type: pkcs12
#    key-store: classpath:ssl/keystore.p12
#    key-store-password: gnteam307
spring:
  application:
    name: discoveryservice
  profiles:
    active: prd

